### ISSUE TITLE
input 데이터 포맷 질문드립니다.

### ISSUE THREAD

**Issue by jaehong-k** [hong8e/KoROUGE#1]
안녕하세요 한국어 요약문 모델의 성능을 평가하는 방법을 찾다가 해당 repository를 찾게되었습니다.
좋은 repository 만들어주심에 감사합니다.
Rouge 스코어 계산시, input 데이터 형식 txt 파일이 적합한지 tsv파일이 적합한지 문의드립니다 :)
감사합니다.

**Comment by hong8e** [comment]
txt 형식으로 하시면 됩니다. 감사합니다.
설치 메뉴얼이 조금 변경되었으니 참고바랍니다.
